#! /usr/bin/env python3

import sys


def get_all_fields(lines, st, end):
    all_fields = []
    all_fields_sizes = []
    for i in range(st, end):
        all_fields_sizes.append([len(f) for f in lines[i].split("|")][1:-1])
        all_fields.append(lines[i].split("|")[1:-1])
    max_sizes = [max(i) for i in zip(*all_fields_sizes)]
    return max_sizes, all_fields


def format_lines(lines, st, end):
    maxs, all_fields = get_all_fields(lines, st, end)
    newlines = ""
    for fields in all_fields:
        newline = ""
        for i, field in enumerate(fields):
            newline = newline + "|" + field
            if len(field) < maxs[i]:
                newline = newline + " " * (maxs[i] - len(field))
        newline = newline + "|"
        newlines = newlines + "".join(newline) + "\n"
    return newlines[:-1]


def main():
    filename = sys.argv[1]
    newlines = []
    with open(filename, "r") as f:
        lines = f.readlines()
        start_format = -1
        for i, line in enumerate(lines):
            line = line.strip()
            if "|" in line:
                if start_format == -1:
                    start_format = i
            else:
                if start_format != -1 and i - start_format > 1:
                    newlines.append(format_lines(lines, start_format, i))
                    start_format = -1
                newlines.append(line)

        if start_format != -1:
            newlines.append(format_lines(lines, start_format, len(lines)))

    with open(filename, "w") as f:
        for line in newlines:
            print(line, file=f)


main()
