#! /usr/bin/env python3

import sys

MAX_LINE_LENGTH = 80


NONE_ST = 0
TABLE_ST = 1
ULIST_ST = 2
TEXTBLOCK_ST = 3
CODEBLOCK_ST = 4
HEADERBLOCK_ST = 5


def get_all_fields(lines):
    all_fields = []
    all_fields_sizes = []
    for line in lines:
        fields = line.split("|")[1:-1]
        all_fields.append(fields)
        all_fields_sizes.append([len(f) for f in fields])

    max_sizes = [max(i) for i in zip(*all_fields_sizes)]
    return max_sizes, all_fields


def format_table(lines):
    maxs, all_fields = get_all_fields(lines)
    newlines = "\n"
    for fields in all_fields:
        newline = ""
        for i, field in enumerate(fields):
            newline = newline + "|" + field
            if len(field) < maxs[i]:
                newline = newline + " " * (maxs[i] - len(field))
        newline = newline + "|"
        newlines = newlines + newline + "\n"
    return newlines[:-1]


def format_text_block(lines):
    newlines = ""
    for line in lines:
        line = line.strip()
        while len(line) > MAX_LINE_LENGTH:
            pos = line.rfind(" ", 0, MAX_LINE_LENGTH + 1)
            if pos != -1:
                newlines = newlines + line[:pos].strip() + "\n"
                line = line[pos:]
            else:
                newlines = newlines + line[:MAX_LINE_LENGTH].strip() + "\n"
                line = line[MAX_LINE_LENGTH:]

        newlines = newlines + line.strip() + "\n"
    return newlines


def get_heading_level(line):
    level = 0
    for c in line:
        if c == "#":
            level = level + 1
        else:
            return level


def is_part_of_text_block(line):
    if line.startswith("#"):
        return False
    if line.startswith("-"):
        return False
    if line.count("|") > 1:
        return False
    return True


def get_leading_spaces(line):
    n = 0
    for c in line:
        if c == " ":
            n = n + 1
        elif c == "\t":
            n = n + 2
        else:
            return "" + " " * n


def main():
    if len(sys.argv) != 3:
        print("Usage: mdformat in.txt out.txt")
        sys.exit(1)

    filename = sys.argv[1]
    if len(sys.argv) > 1:
        outfile = sys.argv[2]

    lines = []
    newlines = []
    with open(filename, "r") as f:
        # add a line to handle textblock or table at end of file without newline
        lines = f.readlines() + [""]

    state = NONE_ST
    start = -1
    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if state == NONE_ST:
            if line.startswith('|'):
                state = TABLE_ST
                start = i

            elif line.startswith("#"):
                level = get_heading_level(line)
                line = "\n" + "#" * level + " " + line[level:].strip()
                newlines.append(line)

            elif line.startswith("---"):
                state = HEADERBLOCK_ST
                newlines.append(line)

            elif line.startswith("-") and not line.startswith("--"):
                ls = get_leading_spaces(lines[i])
                line = ls + "- " + line[1:].strip()
                newlines.append(line)

            elif line:
                state = TEXTBLOCK_ST
                start = i

        elif state == TABLE_ST:
            if not line.startswith('|'):
                if i - start > 1:
                    newlines.append(format_table(lines[start:i]))
                    state = NONE_ST
                    i = i - 1

        elif state == TEXTBLOCK_ST:
            if not is_part_of_text_block(line):
                newlines.append(format_text_block(lines[start:i]).strip())
                state = NONE_ST
                i = i - 1

        elif state == HEADERBLOCK_ST:
            if line.startswith("---"):
                state = NONE_ST
            newlines.append(line)

        i = i + 1

    with open(outfile, "w") as f:
        for line in newlines:
            print(line, file=f)


if __name__ == "__main__":
    main()
